GET http://localhost:3000

###

POST http://localhost:3000/data
Content-Type: application/json

{
     "nama": "Betran"
}

###
POST http://localhost:3000/produk
Content-Type: application/json

{
     "nama": "Produk A",
     "harga": 1000
}

###
GET http://localhost:3000/produk